# Generated by Django 4.1.2 on 2023-06-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_prod', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('id_prod_etiqueta', models.CharField(max_length=15)),
                ('nom_prod', models.CharField(max_length=35)),
                ('precio_prod', models.IntegerField(max_length=7)),
                ('desc_prod', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField(max_length=3)),
            ],
        ),
    ]
