# Generated by Django 4.1.2 on 2023-07-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnticuario', '0004_alter_producto_cantidad_alter_producto_id_prod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='enOferta',
            field=models.BooleanField(default=False),
        ),
    ]
